name: snosey_flutter_package
description: Snosey Private Flutter Package.
version: 0.2.0
homepage: https://github.com/snosey/snosey_flutter_package

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.3
  json_annotation: any
  carousel_slider: ^4.0.0
  flutter_secure_storage: ^4.2.1
  photo_view: ^0.12.0
  get: ^4.3.8
  shimmer: ^2.0.0
  url_launcher: ^6.0.2
  fluttertoast: ^8.0.8
  timeago: ^3.1.0
  intl: ^0.17.0


dev_dependencies:
  build_runner: ^2.1.1
  json_serializable: any
  flutter_test:
    sdk: flutter
